version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: ticket_booking_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"  # Expose PostgreSQL on localhost:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage

  redis:
    image: redis:6.2
    container_name: ticket_booking_redis
    ports:
      - "6379:6379"  # Expose Redis on localhost:6379
    command: ["redis-server", "--appendonly", "yes"]  # Enable persistence for Redis

  mongodb:
    image: mongo:4.4
    container_name: ticket_booking_mongodb
    environment:
      MONGO_INITDB_DATABASE: events_db  # The default database name
    ports:
      - "27017:27017"  # Expose MongoDB on localhost:27017
    volumes:
      - events_db:/data/db  # Persistent storage

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: ticket_booking_rabbitmq
    ports:
      - "5672:5672"      # RabbitMQ default AMQP port
      - "15672:15672"    # RabbitMQ Management plugin UI (HTTP)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - rabbitmq-net

volumes:
  postgres_data:
  events_db:
  rabbitmq-data: